apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: amananiket-com-tls
spec:
  secretName: amananiket-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: amananiket.com
  dnsNames:
    - kubernetes.amananiket.com
    - amananiket.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kubernetes.amananiket.com
          - amananiket.com
